Amazon Connector/src/objects/Credentials__c.object
<CustomObject>
    <fields>
        <fullName>Credentials__c</fullName>
        <label>Credentials</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipName>Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipName>Credentials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ENS_Credentials</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Credentials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ENS_Credentials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Amazon Connector/src/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>TransactionScope__c</fullName>
        <label>Transaction Scope</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ENS_Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ENS_Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Amazon Connector/src/objects/System__c.object
<CustomObject>
    <description>The content mapping object will have the references to the external system for which the mapping is provided. The System object will store information with respect to the External System.</description>
    <label>ENS_System</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ENS_Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Amazon Connector/src/classes/AmazonContentRetrieverBatch.cls
/** 
 *  Description : Batch class to fetch contents from AmazonS3 for all new events and make them ready.This would be called from ScheduleEventHandler class. 
 *
 *  Revision History:
 *
 *  Version          Author              Date                Description
 *  1.0              Vishal Prasad       26/06/2014          Initial Draft
 */
public class AmazonContentRetrieverBatch implements Database.Batchable<EventBean>,Database.Stateful,EventInterface,Database.AllowsCallouts{

    private static final string AMAZON_SERVICE = 'Amazon';
    public List<EventBean> eBeanList;
    public Map<Id, Credentials__c> sysCredMap;
    public AmazonContentRetrieverBatch(){}
    public AmazonContentRetrieverBatch(List<EventBean> eList, Map<Id, System__c> sMap){
          eBeanList = new List<EventBean>();
          sysCredMap = new Map<Id, Credentials__c>();
          eBeanList.addAll(eList);          
          for(ID sid : sMap.keySet()){
          	 
               System__c amazonSys = sMap.get(sid);
               for(Credentials__c credInst : amazonSys.Credentials__r){                     
                     if(credInst.Service__r.Name != null && credInst.Service__r.Name.equalsIgnoreCase(AMAZON_SERVICE)){
                           sysCredMap.put(sid,credInst);
                     }
               }
          } 
    }
    
    /**
     * Iterative start method. 
     * It will iterate over list of EventBean Object considering defined scope.
     */
    public Iterable<EventBean> start(Database.BatchableContext BC) { 
          return eBeanList;
    }
    
    /**
     * Execute Method. 
     * Argument : List<EventBean> 
     * Call AmazonInfoRetriever Class to perform HTTP Call out to AmazonS3 and update EventList
     */
    public void execute(Database.BatchableContext BC, List<EventBean> scope){
          AmazonHandler_clone.getInfo(scope,sysCredMap);
    }
    
    public void finish(Database.BatchableContext BC){
          AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
          //Send an email to the Apex job's submitter notifying of job completion.
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          String[] toAddresses = new String[] {a.CreatedBy.Email};
          mail.setToAddresses(toAddresses);
          mail.setSubject('Amazon Content Retriever Batch Status: ' + a.Status);
          mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.');
         // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    /* Method to call batch class and pass arugments to its parameterised constructor.
     * This method is declared in EventInterface.
     */
    public void newEventBatchExecute(List<EventBean> ebList,Service__c sInst,Map<Id,System__c> sysMap){
          AmazonContentRetrieverBatch batchObj = new AmazonContentRetrieverBatch (ebList,sysMap);
          Id batchId = Database.executeBatch(batchObj,Integer.valueOf(sInst.TransactionScope__c));
    }
    
    public void newEventBatchExecute(CredentialWrapper cred) {

    }
}